theme: jekyll-theme-cayman

title: Devansh Shukla

author: devanshshukla99

navbar links:
Home: "devanshshukla99.github.io"
About Me: "aboutme" 

avatar: "https://avatars0.githubusercontent.com/u/48386249?s=400&v=4"
round-avatar: true
